theme: jekyll-theme-cayman
title: Naming Convention Validation
description: A UE4 plugin to validate naming convention for the assets in your project.

author:
  name:       Michael Delva
  url:        https://www.emidee.net/